#!/bin/sh

# Do not background the xrdb command within xinitrc
#xrdb $HOME/.config/X11/xresources

# Define autostart commands
AUTOSTART="\
dwmblocks
remaps
sxhkd
ibus-daemon -drx
picom
unclutter
xwallpaper --zoom $HOME/.local/dotfiles/wallpaper.png
"

IFS="
" # split on newline

# Run autostart commands
for command in $AUTOSTART; do
    program="$(echo "$command" | cut -d" " -f1)"
    pidof -sx "$program" || eval "$command &"
done >/dev/null 2>&1

# Activate dbus variables
dbus-update-activation-environment --all

# Run dwm
exec dbus-launch --exit-with-session dwm
