#!/bin/sh

# Do not background the xrdb command within xinitrc
#xrdb $HOME/.config/X11/xresources

# Define autostart commands
AUTOSTART="\
dwmblocks
remaps
ibus-daemon -drx
picom
dunst
unclutter
xwallpaper --zoom $HOME/.local/dotfiles/wallpaper.png
"

IFS="
" # split on newline

# Run autostart commands
for command in $AUTOSTART; do
    program="$(echo "$command" | cut -d" " -f1)"
    pidof -sx "$program" || eval "$command &"
done >/dev/null 2>&1

# Run dwm
exec dwm
